#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const directory = dirname(fileURLToPath(import.meta.url));
const repository = resolve(directory, "../../..");
const runtime = resolve(directory, "runtime");
const marker = join(runtime, ".zentext-field-test-runtime");
const projectDirectory = join(runtime, "project");
const packageDirectory = join(runtime, "package");
const cleanNpmEnvironment = Object.fromEntries(
  Object.entries(process.env).filter(
    ([key, value]) =>
      value !== undefined && !key.toLowerCase().startsWith("npm_config_"),
  ),
);

if (existsSync(runtime) && !existsSync(marker)) {
  throw new Error(`Refusing to replace unmarked field-test runtime: ${runtime}`);
}
rmSync(runtime, { recursive: true, force: true });
mkdirSync(runtime, { recursive: true });
writeFileSync(marker, "generated by trusted-memory-cross-tool/prepare.mjs\n");
mkdirSync(packageDirectory, { recursive: true });

const npm = process.platform === "win32" ? "npm.cmd" : "npm";
const packedName = execFileSync(
  npm,
  ["pack", "--silent", "--pack-destination", packageDirectory],
  { cwd: repository, env: cleanNpmEnvironment, encoding: "utf8" },
).trim().split("\n").at(-1);
if (!packedName) throw new Error("npm pack did not return a tarball name.");
const tarball = join(packageDirectory, packedName);

cpSync(join(directory, "project-template"), projectDirectory, {
  recursive: true,
});
mkdirSync(join(projectDirectory, ".agents/skills"), { recursive: true });
cpSync(
  join(repository, ".agents/skills/zentext-memory"),
  join(projectDirectory, ".agents/skills/zentext-memory"),
  { recursive: true },
);
execFileSync(
  npm,
  ["install", "--no-audit", "--no-fund", tarball],
  { cwd: projectDirectory, env: cleanNpmEnvironment, stdio: "pipe" },
);

execFileSync("git", ["init", "-q"], { cwd: projectDirectory });
execFileSync("git", ["config", "user.name", "Zentext Field Test"], {
  cwd: projectDirectory,
});
execFileSync("git", ["config", "user.email", "field-test@example.invalid"], {
  cwd: projectDirectory,
});
const runId = new Date().toISOString().replace(/[^0-9]/gu, "").slice(0, 14);
execFileSync(
  "git",
  [
    "remote",
    "add",
    "origin",
    `https://example.invalid/zentext-trusted-memory-${runId}.git`,
  ],
  { cwd: projectDirectory },
);
mkdirSync(join(projectDirectory, "work"), { recursive: true });
writeFileSync(
  join(projectDirectory, "work/report.md"),
  "# Regional continuity report\n\nTotal: 0\n",
);
writeFileSync(
  join(projectDirectory, "work/verification.log"),
  "Tool A: fixture contains four ordered sources (passed)\n",
);

const zentext = join(projectDirectory, "node_modules/.bin/zentext");
execFileSync(zentext, ["init"], { cwd: projectDirectory, stdio: "pipe" });
execFileSync(
  zentext,
  [
    "task",
    "create",
    "--title",
    "Complete the four-region continuity report",
    "--goal",
    "Record Alpha, Beta, Gamma, and Delta in source order and verify the total.",
  ],
  { cwd: projectDirectory, stdio: "pipe" },
);

const moduleUrl = pathToFileURL(
  join(projectDirectory, "node_modules/zentext/dist/index.js"),
).href;
const { openProject } = await import(moduleUrl);
const project = await openProject({ cwd: projectDirectory });
let setup;
try {
  const task = await project.getActiveTask();
  if (!task) throw new Error("The field-test task was not created.");
  const result = await project.recordProgress({
    task_id: task.id,
    expected_revision: task.revision,
    source_environment: "tool-a-setup",
    completed: [
      "Created the regional report structure",
      "Verified all four deterministic source fixtures are present"
    ],
    changed_files: ["work/report.md", "work/verification.log"],
    blockers: [
      {
        title: "Alpha remains",
        blocker: "The Alpha source has not been read.",
        severity: "medium"
      }
    ],
    verification: [
      {
        check: "Fixture inventory",
        result: "passed",
        summary: "Alpha, Beta, Gamma, and Delta sources are present."
      },
      {
        check: "Initial report",
        result: "passed",
        summary: "The report contains one zero-value Total line."
      }
    ],
    stopping_point:
      "The report structure is ready; no regional source has been read.",
    next_action:
      "Read fixture/source-alpha.txt, append Alpha to work/report.md, update Total, and verify the report.",
    accepted_decisions: [
      {
        title: "Preserve source order",
        decision: "Keep Alpha, Beta, Gamma, and Delta in that order.",
        rationale: "Every participant must be able to audit the serial continuation."
      }
    ],
    files_inspected: [
      "fixture/source-alpha.txt",
      "fixture/source-beta.txt",
      "fixture/source-gamma.txt",
      "fixture/source-delta.txt"
    ],
    commands_executed: ["Confirmed four fixture files exist"],
  });
  setup = {
    project_id: project.meta.projectId,
    task_id: result.task.id,
    starting_revision: result.task.revision,
    original_handoff_id: result.handoff.record_id,
  };
} finally {
  project.close();
}

execFileSync("git", ["add", "."], { cwd: projectDirectory });
execFileSync("git", ["commit", "-q", "-m", "test: seed trusted-memory fixture"], {
  cwd: projectDirectory,
});

const scenario = JSON.parse(
  readFileSync(join(directory, "scenario.json"), "utf8"),
);
const manifest = {
  schema_version: 1,
  package: packedName,
  node: process.version,
  exact_prompt: scenario.exact_prompt,
  ...setup,
};
writeFileSync(
  join(runtime, "manifest.json"),
  `${JSON.stringify(manifest, null, 2)}\n`,
);
process.stdout.write(
  `${JSON.stringify(
    {
      ...manifest,
      runtime: "<field-test-runtime>",
      project: "<field-test-project>",
    },
    null,
    2,
  )}\n`,
);
